# boss bar text per world
text:
  world: "§eYou can edit this text in config.yml"
  nether: "§eYou can edit this text in config.yml"
# boss bar length
length: 100
# boss bar color (1.18+)
# available: PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE
color: DEFAULT
